ABProject\DirectoryGEABundle\Entity\Activite:
  type: entity
  table: activite
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    nom_activite:
      type: string
      length: 255
      nullable: false
    type_activite:
      type: string
      length: 255
      nullable: false
  oneToMany:
    activite_realisees:
      targetEntity: ActiviteRealisee
      mappedBy: activite