ABProject\DirectoryGEABundle\Entity\Activite:
  type: entity
  table: activite
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  oneToMany:
    etudiants:
      targetEntity: Etudiant
      mappedBy: activite
  fields:
    nom_activite:
      type: string
      length: 255
      nullable: false
    type_activite:
      type: string
      length: 255
      nullable: false
    annee_debut:
      type: integer
      length: 4
      nullable: true
    annee_fin:
      type: integer
      length: 4
      nullable: true
    description:
      type: string
      length: 255
      nullable: true