ABProject\DirectoryGEABundle\Entity\ActiviteRealisee:
  type: entity
  table: activite_realisee
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  manyToOne:
    etudiant:
      targetEntity: Etudiant
      inversedBy: activite_realisees
      joinColumn:
        name: etudiant_id
        referencedColumnName: id
      nullable: false
    activite:
      targetEntity: Activite
      inversedBy: activite_realisees
      joinColumn:
        name: activite_id
        referencedColumnName: id
      nullable: false
  fields:
    annee_debut:
      type: integer
      length: 4
      nullable: true
    annee_fin:
      type: integer
      length: 4
      nullable: true
    description:
      type: string
      length: 255
      nullable: true