ABProject\DirectoryGEABundle\Entity\Promotion:
  type: entity
  repositoryClass: ABProject\DirectoryGEABundle\Repository\PromotionRepository
  table: promotion
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    nom_promotion:
      type: string
      length: 255
    annee_promotion:
      type: integer
      length: 4
    slug:
      type: string
      length: 255
      unique: true
  oneToMany:
    etudiants:
      targetEntity: Etudiant
      mappedBy: promotion
  lifecycleCallbacks:
    prePersist: [ setSlugValue ]
    preUpdate: [ setSlugValue ]