ABProject\DirectoryGEABundle\Entity\Specialite:
  type: entity
  repositoryClass: ABProject\DirectoryGEABundle\Repository\SpecialiteRepository
  table: specialite
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    nom_specialite:
      type: string
      length: 255
      unique: true
      nullable: false
    slug:
      type: string
      length: 255
      unique: true
  oneToMany:
    etudiants:
      targetEntity: Etudiant
      mappedBy: specialite
  lifecycleCallbacks:
    prePersist: [ setSlugValue ]
    preUpdate: [ setSlugValue ]