<?php

namespace ABProject\DirectoryGEABundle\Repository;

use Doctrine\ORM\EntityRepository;
use ABProject\DirectoryGEABundle\Entity\Etudiant;

/**
 * EtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRepository extends EntityRepository
{
	public function getForLuceneQuery($query)
    {
        $hits = Etudiant::getLuceneIndex()->find($query);
 
        $pks = array();
        foreach ($hits as $hit)
        {
          $pks[] = $hit->pk;
        }
 
        if (empty($pks))
        {
          return array();
        }
 
        $q = $this->createQueryBuilder('e')
            ->where('e.id IN (:pks)')
            ->setParameter('pks', $pks)
            ->getQuery();
 
        return $q->getResult();
    }
}
