<?php

namespace ABProject\DirectoryGEABundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository
{
	public function getWithStudents()
	  {
	    $query = $this->getEntityManager()->createQuery('SELECT c FROM ABProjectDirectoryGEABundle:Promotion c LEFT JOIN c.etudiants');
	 
	    return $query->getResult();
	  }
}
