etudiant:
    path:     /
    defaults: { _controller: "ABProjectDirectoryGEABundle:Etudiant:index" }

etudiant_show:
    path:     /{id}/show
    defaults: { _controller: "ABProjectDirectoryGEABundle:Etudiant:show" }

etudiant_search:
    pattern: /search
    defaults: { _controller: "ABProjectDirectoryGEABundle:Etudiant:search" }