ab_project_directory_gea_etudiant:
    resource: "@ABProjectDirectoryGEABundle/Resources/config/routing/etudiant.yml"
    prefix:   /etudiant

ab_project_directory_gea_homepage:
    path:     /
    defaults: { _controller: ABProjectDirectoryGEABundle:Default:index }

ab_project_directory_gea_contact:
    path:     /contact
    defaults: { _controller: ABProjectDirectoryGEABundle:Contact:contact }

ab_project_directory_gea_specialite:
    path:     /specialite/{slug}
    defaults: { _controller: ABProjectDirectoryGEABundle:Specialite:show }